version: "3"
services:
  iot-smartphone-app:
        build: iot-smartphone-app/.
        restart: always
        ports:
          - 3005:3000
        environment:
          - BROKER_URL=192.168.178.88
          - BROKER_PORT=9001
  iot-subscriber:
        build: iot-subscriber/.
        ports:
          - '5000:5000'
        restart: always
        environment:
          - BROKER_URL=mosquitto
          - MQTT_PORT=1883
          - MQTT_TRAIN_TOPIC=train/#
        env_file:
          - pg-datenbank.env
  inference-app:
        build: inference-app/.
        ports:
          - '4000:4000'
        restart: always
        environment:
          - BROKER_URL=mosquitto
          - MQTT_PORT=1883
          - MQTT_INFER_TOPIC=inference/#
        env_file:
          - pg-datenbank.env
          - ibm-wml.env
  mosquitto:
        build: mosquitto-broker/.
        ports:
          - '1883:1883'
          - '9001:9001'
          - '8883:8883'
        restart: always
  test-db:
        build: test-db/.
        ports:
          - '5001:5000'
        restart: always
        environment:
          - MQTT_INFER_TOPIC=inference/#
        env_file:
          - pg-datenbank.env