version: "3"
services:
  iot-smartphone-app:
        build: iot-smartphone-app/.
        restart: always
        ports:
          - 3000:3000
        environment:
          - LOCALIP=192.168.178.88
  iot-subscriber:
        build: iot-subscriber/.
        ports:
          - '5000:5000'
        restart: always
        environment:
          - BROKER_URL=mosquitto
          - MQTT_PORT=1883
          - MQTT_TOPIC=smartphone/#
        env_file:
          - pg-datenbank.env
  mosquitto:
        build: mosquitto-broker/.
        ports:
          - '1883:1883'
          - '9001:9001'
          - '8883:8883'
        restart: always
  test-db:
      build: test-db/.
      ports:
        - '5001:5000'
      restart: always
      env_file:
        - pg-datenbank.env