apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: sensorapp-dummymax
  labels:
    app: sensorapp  
data:
  mosquitto.conf: |    
    persistence false
    # mqtt
    listener 1883
    protocol mqtt
    # websockets
    # websockets over ssl
    listener 8883
    protocol websockets
    certfile /etc/mosquitto/certs/certfile_default.pem
    cafile /etc/mosquitto/certs/cafile_default_intermediate.pem
    keyfile /etc/mosquitto/certs/keyfile_default.key
    allow_anonymous true